version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  build:
    docker:
      - image: node:10

    working_directory: ~/repo

    steps:
      - browser-tools/install-chrome:
          channel: stable 
          replace-existing: false 

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # we need to install CircleCI CLI tool
      # to run the "manual" tests
      - circleci-cli/install
      - run: npm test
      - run: npm run manual:tests
      - run: npm run docs

workflows:
  orb_tests:
    jobs:
      - orb_tests build
